package com.example.ui.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFFC00011)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onPrimaryContainer = Color(0xFF410002)
internal val md_theme_light_secondary = Color(0xFF775652)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onSecondaryContainer = Color(0xFF2C1512)
internal val md_theme_light_tertiary = Color(0xFF715B2E)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFFDDFA6)
internal val md_theme_light_onTertiaryContainer = Color(0xFF261900)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFFFBFF)
internal val md_theme_light_onBackground = Color(0xFF201A19)
internal val md_theme_light_surface = Color(0xFFFFFBFF)
internal val md_theme_light_onSurface = Color(0xFF201A19)
internal val md_theme_light_surfaceVariant = Color(0xFFF5DDDA)
internal val md_theme_light_onSurfaceVariant = Color(0xFF534341)
internal val md_theme_light_outline = Color(0xFF857371)
internal val md_theme_light_inverseOnSurface = Color(0xFFFBEEEC)
internal val md_theme_light_inverseSurface = Color(0xFF362F2E)
internal val md_theme_light_inversePrimary = Color(0xFFFFB4AB)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFFC00011)
internal val md_theme_light_outlineVariant = Color(0xFFD8C2BF)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFFFFB4AB)
internal val md_theme_dark_onPrimary = Color(0xFF690005)
internal val md_theme_dark_primaryContainer = Color(0xFF93000A)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_secondary = Color(0xFFE7BDB8)
internal val md_theme_dark_onSecondary = Color(0xFF442926)
internal val md_theme_dark_secondaryContainer = Color(0xFF5D3F3C)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_tertiary = Color(0xFFE0C38C)
internal val md_theme_dark_onTertiary = Color(0xFF3F2E04)
internal val md_theme_dark_tertiaryContainer = Color(0xFF574419)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFFDDFA6)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF201A19)
internal val md_theme_dark_onBackground = Color(0xFFEDE0DE)
internal val md_theme_dark_surface = Color(0xFF201A19)
internal val md_theme_dark_onSurface = Color(0xFFEDE0DE)
internal val md_theme_dark_surfaceVariant = Color(0xFF534341)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFD8C2BF)
internal val md_theme_dark_outline = Color(0xFFA08C8A)
internal val md_theme_dark_inverseOnSurface = Color(0xFF201A19)
internal val md_theme_dark_inverseSurface = Color(0xFFEDE0DE)
internal val md_theme_dark_inversePrimary = Color(0xFFC00011)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFFFFB4AB)
internal val md_theme_dark_outlineVariant = Color(0xFF534341)
internal val md_theme_dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFFEF0018)
