package com.example.ui.theme

import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFF904A43)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFFFDAD6)
internal val onPrimaryContainerLight = Color(0xFF3B0907)
internal val secondaryLight = Color(0xFF775652)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFFFDAD6)
internal val onSecondaryContainerLight = Color(0xFF2C1512)
internal val tertiaryLight = Color(0xFF715B2E)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFFDDFA6)
internal val onTertiaryContainerLight = Color(0xFF261900)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF410002)
internal val backgroundLight = Color(0xFFFFF8F7)
internal val onBackgroundLight = Color(0xFF231918)
internal val surfaceLight = Color(0xFFFFF8F7)
internal val onSurfaceLight = Color(0xFF231918)
internal val surfaceVariantLight = Color(0xFFF5DDDA)
internal val onSurfaceVariantLight = Color(0xFF534341)
internal val outlineLight = Color(0xFF857371)
internal val outlineVariantLight = Color(0xFFD8C2BF)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF392E2D)
internal val inverseOnSurfaceLight = Color(0xFFFFEDEA)
internal val inversePrimaryLight = Color(0xFFFFB4AB)
internal val surfaceDimLight = Color(0xFFE8D6D4)
internal val surfaceBrightLight = Color(0xFFFFF8F7)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFFFF0EE)
internal val surfaceContainerLight = Color(0xFFFCEAE7)
internal val surfaceContainerHighLight = Color(0xFFF6E4E2)
internal val surfaceContainerHighestLight = Color(0xFFF1DEDC)

internal val primaryDark = Color(0xFFFFB4AB)
internal val onPrimaryDark = Color(0xFF561E19)
internal val primaryContainerDark = Color(0xFF73332D)
internal val onPrimaryContainerDark = Color(0xFFFFDAD6)
internal val secondaryDark = Color(0xFFE7BDB8)
internal val onSecondaryDark = Color(0xFF442926)
internal val secondaryContainerDark = Color(0xFF5D3F3C)
internal val onSecondaryContainerDark = Color(0xFFFFDAD6)
internal val tertiaryDark = Color(0xFFE0C38C)
internal val onTertiaryDark = Color(0xFF3F2E04)
internal val tertiaryContainerDark = Color(0xFF574419)
internal val onTertiaryContainerDark = Color(0xFFFDDFA6)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF1A1110)
internal val onBackgroundDark = Color(0xFFF1DEDC)
internal val surfaceDark = Color(0xFF1A1110)
internal val onSurfaceDark = Color(0xFFF1DEDC)
internal val surfaceVariantDark = Color(0xFF534341)
internal val onSurfaceVariantDark = Color(0xFFD8C2BF)
internal val outlineDark = Color(0xFFA08C8A)
internal val outlineVariantDark = Color(0xFF534341)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFF1DEDC)
internal val inverseOnSurfaceDark = Color(0xFF392E2D)
internal val inversePrimaryDark = Color(0xFF904A43)
internal val surfaceDimDark = Color(0xFF1A1110)
internal val surfaceBrightDark = Color(0xFF423735)
internal val surfaceContainerLowestDark = Color(0xFF140C0B)
internal val surfaceContainerLowDark = Color(0xFF231918)
internal val surfaceContainerDark = Color(0xFF271D1C)
internal val surfaceContainerHighDark = Color(0xFF322826)
internal val surfaceContainerHighestDark = Color(0xFF3D3231)


internal val seed = Color(0xFFC00011)
